
[Multiplier]
	#Xp multiplier see here : https://1drv.ms/x/s!Aq5o6W9h7OB9gYExyFZm1cFhJ0n0EA?e=zVMCg7
	"XP Multiplier" = 1.095
	#Won XP multiplier see here : https://1drv.ms/x/s!Aq5o6W9h7OB9gYExyFZm1cFhJ0n0EA?e=zVMCg7
	"Won XP Multiplier" = 0.982

["Won Level"]
	#Example "minecraft:diamond 12, minecraft:iron_sword 1" Please separe each item by ", " ! The "," and the space is very important
	"Item give each level" = "minecraft:air 64"

