modLoader="javafml"
loaderVersion="[2,)"
license="MIT License"

[[mods]]
modId="erinium_automation"
version="1.0.4"
displayName="eriunium_automation"
displayURL="https://legacy.curseforge.com/minecraft/mc-mods/erinium-automation"
logoFile="logo.png"
credits="Created thanks to MCreator"
authors="JLSkyzer"
description="Mod created by JLSkyzer"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.erinium_automation]]
    modId="neoforge"
    type="required"
    versionRange="[20.4.223,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.erinium_automation]]
    modId="minecraft"
    type="required"
    versionRange="[1.20.4]"
    ordering="NONE"
    side="BOTH"

[[dependencies.erinium_automation]]
    modId="mekanism"
    type="required"
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


