modLoader="javafml"
loaderVersion="[47,)"
license="MIT License"

[[mods]]
modId="erinium_automation"
version="1.0.2"
displayName="eriunium_automation"
credits="Created thanks to MCreator"
displayURL="https://legacy.curseforge.com/minecraft/mc-mods/erinium-automation"
logoFile="logo.png"
authors="JLSkyzer"
description="Mod created by JLSkyzer"

[[dependencies.erinium_automation]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"


[[dependencies.erinium_automation]]
    modId="mekanism"
    mandatory=true
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.erinium_automation]]
    modId="crafttweaker"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

