modLoader="javafml"
loaderVersion="[2,)"
license="Not specified"

[[mods]]
modId="eriniumroleplay"
version="1.0.0"
displayName="EriniumRolePlay"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="killi, MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.eriniumroleplay]]
    modId="neoforge"
    type="required"
    versionRange="[20.4.223,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.eriniumroleplay]]
    modId="minecraft"
    type="required"
    versionRange="[1.20.4]"
    ordering="NONE"
    side="BOTH"




[[mixins]]
    config="mixins.eriniumroleplay.json"