modLoader="javafml"
loaderVersion="[2,)"
license="Academic Free License v3.0"

[[mods]]
modId="erinium_faction"
version="1.1.0"
displayName="Erinium Faction Mod"
displayURL="https://github.com/JLSkyzer"
credits="No credit"
authors="JLSkyzer, MCreator"
description="A mod for faction system"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.erinium_faction]]
    modId="neoforge"
    type="required"
    versionRange="[20.4.223,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.erinium_faction]]
    modId="minecraft"
    type="required"
    versionRange="[1.20.4]"
    ordering="NONE"
    side="BOTH"



