modLoader="javafml"
loaderVersion="[47,)"
license="Academic Free License v3.0"

[[mods]]
modId="erinium_faction"
version="1.0.2"
displayName="Erinium Faction Mod"
displayURL="https://github.com/JLSkyzer"
credits="No credit"
authors="JLSkyzer, MCreator"
description="A mod for faction system"

[[dependencies.erinium_faction]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"



[[dependencies.erinium_faction]]
    modId="jsonforhttprequest"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

